export const paletteColors = [
  { name: "red", active: true, colorCode: "#F44336" },
  { name: "pink", active: false, colorCode: "#E91E63" },
  { name: "purple", active: false, colorCode: "#9C27B0" },
  { name: "deep purple", active: false, colorCode: "#673AB7" },
  { name: "indigo", active: false, colorCode: "#3F51B5" },
  { name: "blue", active: false, colorCode: "#2196F3" },
  { name: "light blue", active: false, colorCode: "#03A9F4" },
  { name: "cyan", active: false, colorCode: "#00BCD4" },
  { name: "teal", active: false, colorCode: "#009688" },
  { name: "green", active: false, colorCode: "#4CAF50" },
  { name: "light green", active: false, colorCode: "#8BC34A" },
  { name: "lime green", active: false, colorCode: "#CDDC39" },
  { name: "yellow", active: false, colorCode: "#FFEB3B" },
  { name: "amber", active: false, colorCode: "#FFC107" },
  { name: "orange", active: false, colorCode: "#FF9800" },
  { name: "deep orange", active: false, colorCode: "#FF5722" },
  { name: "brown", active: false, colorCode: "#795548" },
  { name: "gray", active: false, colorCode: "#9E9E9E" },
  { name: "bleu gray", active: false, colorCode: "#607D8B" },
  { name: "", active: false, colorCode: "#3E474D" },
];

export const paletteShades = [
  {
    name: "red",
    code: "#F44336",
    active: true,
    shades: [
      { id: 1, colorCode: "#B71C1C", active: false, shade: 900 },
      { id: 2, colorCode: "#C62828", active: false, shade: 800 },
      { id: 3, colorCode: "#D32F2F", active: false, shade: 700 },
      { id: 4, colorCode: "#E53935", active: false, shade: 600 },
      { id: 5, colorCode: "#EF5350", active: true, shade: 500 },
      { id: 6, colorCode: "#E57373", active: false, shade: 400 },
      { id: 7, colorCode: "#EF9A9A", active: false, shade: 300 },
      { id: 8, colorCode: "#FFCDD2", active: false, shade: 200 },
      { id: 9, colorCode: "#FFEBEE", active: false, shade: 100 },
    ],
  },
];
